spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clothingcab
    username: root
    password: system123#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


